DROP TABLE IF EXISTS `fraudlabspro`;
CREATE TABLE `fraudlabspro` (
	`order_id` INT(11) NOT NULL,
	`is_country_match` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_high_risk_country` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`distance_in_km` VARCHAR(10) NOT NULL COLLATE 'utf8_bin',
	`distance_in_mile` VARCHAR(10) NOT NULL COLLATE 'utf8_bin',
	`ip_address` VARCHAR(39) NOT NULL COLLATE 'utf8_bin',
	`ip_country` VARCHAR(2) NOT NULL COLLATE 'utf8_bin',
	`ip_continent` VARCHAR(20) NOT NULL COLLATE 'utf8_bin',
	`ip_region` VARCHAR(21) NOT NULL COLLATE 'utf8_bin',
	`ip_city` VARCHAR(21) NOT NULL COLLATE 'utf8_bin',
	`ip_latitude` VARCHAR(21) NOT NULL COLLATE 'utf8_bin',
	`ip_longitude` VARCHAR(21) NOT NULL COLLATE 'utf8_bin',
	`ip_timezone` VARCHAR(10) NOT NULL COLLATE 'utf8_bin',
	`ip_elevation` VARCHAR(10) NOT NULL COLLATE 'utf8_bin',
	`ip_domain` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`ip_mobile_mnc` VARCHAR(100) NOT NULL COLLATE 'utf8_bin',
	`ip_mobile_mcc` VARCHAR(100) NOT NULL COLLATE 'utf8_bin',
	`ip_mobile_brand` VARCHAR(100) NOT NULL COLLATE 'utf8_bin',
	`ip_netspeed` VARCHAR(10) NOT NULL COLLATE 'utf8_bin',
	`ip_isp_name` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`ip_usage_type` VARCHAR(30) NOT NULL COLLATE 'utf8_bin',
	`is_free_email` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_new_domain_name` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_proxy_ip_address` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_bin_found` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_bin_country_match` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_bin_name_match` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_bin_phone_match` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_bin_prepaid` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_address_ship_forward` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_bill_ship_city_match` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_bill_ship_state_match` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_bill_ship_country_match` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_bill_ship_postal_match` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_ip_blacklist` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_email_blacklist` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_credit_card_blacklist` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_device_blacklist` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`is_user_blacklist` CHAR(2) NOT NULL COLLATE 'utf8_bin',
	`fraudlabspro_score` CHAR(3) NOT NULL COLLATE 'utf8_bin',
	`fraudlabspro_distribution` CHAR(3) NOT NULL COLLATE 'utf8_bin',
	`fraudlabspro_status` CHAR(10) NOT NULL COLLATE 'utf8_bin',
	`fraudlabspro_id` CHAR(15) NOT NULL COLLATE 'utf8_bin',
	`fraudlabspro_error_code` CHAR(3) NOT NULL COLLATE 'utf8_bin',
	`fraudlabspro_message` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`fraudlabspro_credits` VARCHAR(10) NOT NULL COLLATE 'utf8_bin',
	`api_key` CHAR(32) NOT NULL COLLATE 'utf8_bin',
	INDEX `idx_order_id` (`order_id`)
) COLLATE='utf8_bin' ENGINE=MyISAM;